#!/bin/bash
#PBS -P vy72
#PBS -N Job_ASDF_build_output
#PBS -q express
#PBS -l walltime=00:08:00,mem=3GB,ncpus=2,jobfs=100MB
#PBS -l wd
#PBS -j oe
#PBS -M ashby.cooper@ga.gov.au
#PBS -m bae

module purge
module load python3/3.6.2
module load openmpi/1.10.2
module load hdf5/1.10.2p
module load mpi4py/3.0.0-py36-omp10.2

export PYTHONPATH=$HOME/.local/lib/python3.6/site-packages/:$PYTHONPATH

mpirun -np 2 python3 ASDF_build_minimus_service_MPI_master.py > ASDF_build_minimus_service_MPI_master.out